name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - 'feature/*'
  
  workflow_dispatch:

permissions:
  contents: read # This is necessary for appropriate permissions to be granted.

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          entryCount: 6
          sortOrder: desc
          mdHeader: |
            ## Latest contributed repos
          jsonFilepath: hot-repos.json
          mdFilepath: hot-repos.md
      
      - name: Check output of topRepos
        run: |
          echo Printing action output;
          cat <<-;
          ${{ steps.test.outputs.topRepos }}
          
          echo printing complete;
        id: json
      
      - name: Check output of markdown
        run: |
          echo Printing action output;
          cat <<-;
          ${{ steps.test.outputs.markdown }}
          
          echo printing complete;
        id: md

      - name: Upload output files
        uses: actions/upload-artifact@v3
        with:
          name: hot-repos
          path: |
            hot-repos.json
            hot-repos.md